os: linux

language: cpp
sudo: required
dist: trusty

branches:
    only:
    - travis-test

before_install:
- ./tests/travis/setup.sh

script:
- ./tests/travis/build.sh

after_success:
- ./tests/travis/install.sh
