language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3
      sudo: required

before_install:
  - travis_wait 30 ./tests/travis/$TRAVIS_OS_NAME/setup.sh

script:
  - ./tests/travis/$TRAVIS_OS_NAME/build.sh

after_success:
  - find . -name "*.qch" #TODO debug

before_deploy:
  - ./tests/travis/$TRAVIS_OS_NAME/upload-prepare.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BTMUeBjCBfDFo3Pysojz2yMFKnK0Lz3wkS3Pa+IfrztWHkWQWxZWqcvj/jGQiwqcuZhGu604E0T8NlOwUHylXxLL1ZE5+eQFXBc7GEmNOZ9Ql3ay9XiYegqYKN9nO9zgtB6QzJ3G3i4FMyQrfiSUaFTlOsosnQkJZJc0AcvW2kdmoNYpfWBGAK/WcejXTI27BnbxXX7nmf3A+yYLbyreAH2wZRt2NNv691tqC7YFL4p2aHOb51J/higTFalgSaI9ClpcXXuPh0S9GHy1CtDRvAxzzs5g1Fvu6FDMfkC+U2ka8l5mPZ5n9jd74PX0ijdFyLkjqOGUne29GvQIxKQZ0tWNHmkh/hKB5UG4MowBFjaomyuIBcifCtiUjkcuW8zHefPXsOxhBFiQWN1TatBCQocdPVCu/hT1PYuX1MFXEMKSRtfcj+ZNQTmtH3riHObZcZvm1a7xNg5WAdulK8O/shUGstlmug94RhJIwj7HQzZ0ko4WWham4uFl9amN4Uwr3Ik87MJXGXsXHznr3RTRmrUkqQY/rPKVIp4ZgfXIQqKZhBNNhUlORzVh52D6OQJd4/c6vKiA3FbDsykKPywr83Q+oTuV881Xv1GgqF9ZFXoeSMeIeIwAOWRJ7zKmJ9oZcko91NE7A+FmPjtOzHFYxWoCMbJtOYJ6nJ02VGmGjC8=
  file:
    - install/opt/build_linux_5.9.1.tar.xz
    - install/opt/build_osx_5.9.1.tar.xz
  on:
    repo: Skycoder42/QJsonSerializer
    branch: travis-test
    tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
