image: Visual Studio 2017

version: 2.2.1-{build}

environment:
  matrix:
  - name: win32
    platform: amd64_x86
    qt: msvc2017

install:
  - .\tests\travis\win\setup.bat

build_script:
  - .\tests\travis\win\build.bat

#artifacts:
#  - path: gopath\bin\qpm.exe
#    name: qpm
