image:
  - Visual Studio 2017
  - Visual Studio 2015

version: 2.2.1-{build}

install:
  - .\tests\travis\win\setup.bat

build_script:
  - .\tests\travis\win\build.bat

artifacts:
  - path: install
    name: build_win_5.9.0
    type: zip
